"use client";

import { useMutation, useQuery } from "@tanstack/react-query";
import { ArrowLeft, Check, CircleAlert, CreditCard, LoaderCircle, Sparkles } from "lucide-react";
import Link from "next/link";
import { createCheckout, getBillingOverview, listPlans } from "@/lib/billing/api";
import type { Plan } from "@/lib/billing/types";
import { getAPIError } from "@/lib/install/api";
import { useBilingual } from "@/lib/i18n";

export function BillingConsole() {
  const t = useBilingual();
  const plans = useQuery({ queryKey: ["billing-plans"], queryFn: listPlans });
  const overview = useQuery({ queryKey: ["billing-overview"], queryFn: getBillingOverview });
  const checkout = useMutation({ mutationFn: createCheckout, onSuccess: ({ url }) => window.location.assign(url) });
  const error = plans.error ?? overview.error ?? checkout.error;

  return <main className="min-h-screen bg-canvas p-5 text-ink sm:p-10"><div className="mx-auto max-w-[1400px]">
    <Link className="inline-flex items-center gap-2 text-xs font-bold" href="/admin"><ArrowLeft className="size-4" />{t("返回后台", "Back to admin")}</Link>
    <header className="mt-10 flex flex-col justify-between gap-5 border-b border-ink/15 pb-6 md:flex-row md:items-end"><div><p className="install-kicker">SUBSCRIPTION / USAGE</p><h1 className="mt-3 text-4xl font-black tracking-[-.055em] sm:text-6xl">{t("套餐与用量", "Plans & usage")}</h1><p className="mt-3 max-w-2xl text-sm leading-7 text-ink-muted">{t("配额在服务端原子计量；升级只有在 Stripe Webhook 验签并落库后生效。", "Usage is measured atomically on the server. Upgrades take effect only after the Stripe webhook is verified and persisted.")}</p></div>{overview.data && <div className="border border-ink/15 bg-ink px-5 py-4 text-white"><p className="font-mono text-[9px] text-signal">{t("当前套餐", "CURRENT PLAN")}</p><p className="mt-1 text-2xl font-black">{overview.data.plan.name}</p><p className="mt-1 text-[10px] text-white/45">{overview.data.subscription.status} · {t("到期", "Ends")} {new Date(overview.data.subscription.period_end).toLocaleDateString()}</p></div>}</header>
    {error && <div className="mt-6 flex gap-2 border-l-2 border-red-800 bg-red-50 p-4 text-xs text-red-900"><CircleAlert className="size-4" />{getAPIError(error)}</div>}{overview.isLoading && <LoaderCircle className="mt-8 size-5 animate-spin" />}
    {overview.data && <section className="mt-7 grid gap-4 md:grid-cols-2 xl:grid-cols-4"><Usage label={t("用户席位", "User seats")} value={overview.data.usage.users ?? 0} limit={overview.data.plan.max_users} /><Usage label={t("业务记录", "Business records")} value={overview.data.usage.records ?? 0} limit={overview.data.plan.max_records} /><Usage label={t("知识库", "Knowledge")} value={overview.data.usage.knowledge_bytes ?? 0} limit={overview.data.plan.max_knowledge_bytes} bytes /><Usage label="AI Tokens" value={overview.data.usage.ai_tokens ?? 0} limit={overview.data.plan.max_ai_tokens} /></section>}
    <section className="mt-10"><div className="flex items-center gap-2"><Sparkles className="size-4 text-signal" /><h2 className="text-xl font-black">{t("可用套餐", "Available plans")}</h2></div><div className="mt-5 grid gap-4 lg:grid-cols-3">{plans.data?.map((plan) => <PlanCard plan={plan} current={overview.data?.plan.code === plan.code} pending={checkout.isPending} choose={() => checkout.mutate(plan.code)} t={t} key={plan.id} />)}</div></section>
    <p className="mt-8 border-t border-ink/15 pt-5 text-[10px] leading-6 text-ink-muted">{t("Community 套餐适合开源私有部署。付费套餐需要服务端配置 Stripe Secret、Webhook Secret 与对应 Price ID；Checkout 返回不代表订阅已激活，以验签 Webhook 为准。", "The Community plan suits self-hosted open-source deployments. Paid plans require Stripe Secret, Webhook Secret, and matching Price IDs. A checkout response does not activate a subscription; the verified webhook is authoritative.")}</p>
  </div></main>;
}

function Usage({ label, value, limit, bytes = false }: { label: string; value: number; limit: number; bytes?: boolean }) { const percent = Math.min(100, limit > 0 ? value / limit * 100 : 0); return <article className="border border-ink/15 bg-white/35 p-5"><p className="font-mono text-[9px] text-ink-muted">{label.toUpperCase()}</p><p className="mt-3 text-2xl font-black">{bytes ? formatBytes(value) : value.toLocaleString()} <span className="text-xs font-normal text-ink-muted">/ {bytes ? formatBytes(limit) : limit.toLocaleString()}</span></p><div className="mt-4 h-1.5 bg-ink/10"><div className={`h-full ${percent > 85 ? "bg-red-700" : "bg-signal"}`} style={{ width: `${percent}%` }} /></div></article>; }
function PlanCard({ plan, current, pending, choose, t }: { plan: Plan; current: boolean; pending: boolean; choose: () => void; t: (zh: string, en: string) => string }) { return <article className={`border p-6 ${current ? "border-signal bg-ink text-white" : "border-ink/15 bg-white/35"}`}><div className="flex items-center justify-between"><h3 className="text-2xl font-black">{plan.name}</h3>{current && <span className="font-mono text-[9px] text-signal">{t("当前", "CURRENT")}</span>}</div><p className="mt-4 text-4xl font-black">${(plan.price_cents / 100).toFixed(0)}<span className="text-xs font-normal opacity-50"> {t("/ 月", "/ month")}</span></p><div className="mt-6 space-y-2 text-xs opacity-70"><p><Check className="mr-2 inline size-3" />{plan.max_users.toLocaleString()} {t("用户", "users")}</p><p><Check className="mr-2 inline size-3" />{plan.max_records.toLocaleString()} {t("记录", "records")}</p><p><Check className="mr-2 inline size-3" />{formatBytes(plan.max_knowledge_bytes)} {t("知识", "knowledge")}</p><p><Check className="mr-2 inline size-3" />{plan.max_ai_tokens.toLocaleString()} AI Tokens</p></div><button className={current ? "mt-7 w-full border border-white/20 px-4 py-3 text-xs" : "install-button-primary mt-7 w-full"} disabled={current || plan.price_cents === 0 || pending} onClick={choose}>{current ? t("当前套餐", "Current plan") : plan.price_cents === 0 ? t("免费开源", "Free & open source") : t("使用 Stripe 升级", "Upgrade with Stripe")}{!current && plan.price_cents > 0 && <CreditCard className="size-4" />}</button></article>; }
function formatBytes(value: number) { return value >= 1024 ** 3 ? `${(value / 1024 ** 3).toFixed(1)} GB` : `${Math.ceil(value / 1024 ** 2)} MB`; }
