"use client";

import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { ArrowLeft, Check, LoaderCircle, ShieldCheck } from "lucide-react";
import Link from "next/link";
import { useState } from "react";
import { getPermissions, getRoles, setRolePermissions } from "@/lib/auth/api";
import { useAuthStore } from "@/lib/auth/store";

export function AccessControl() {
  const queryClient = useQueryClient(); const accessToken = useAuthStore((state) => state.accessToken); const roles = useQuery({ queryKey: ["roles"], queryFn: getRoles, enabled: Boolean(accessToken) }); const permissions = useQuery({ queryKey: ["permissions"], queryFn: getPermissions, enabled: Boolean(accessToken) });
  const [draft, setDraft] = useState<{ roleID: string; permissions: string[] } | null>(null);
  const selectedRoleID = draft?.roleID ?? roles.data?.[0]?.id ?? "";
  const selectedRole = roles.data?.find((role) => role.id === selectedRoleID);
  const selectedPermissions = draft?.roleID === selectedRoleID ? draft.permissions : selectedRole?.permissions ?? [];
  const mutation = useMutation({ mutationFn: () => setRolePermissions(selectedRoleID, selectedPermissions), onSuccess: () => queryClient.invalidateQueries({ queryKey: ["roles"] }) });
  if (!accessToken) return <main className="grid min-h-screen place-items-center bg-ink font-mono text-xs text-white/40">AUTHENTICATION REQUIRED</main>;
  return <main className="min-h-screen bg-canvas p-5 text-ink sm:p-10"><div className="mx-auto max-w-6xl"><Link className="inline-flex items-center gap-2 text-xs font-bold" href="/admin"><ArrowLeft className="size-4" />返回后台</Link><div className="mt-10 flex items-end justify-between gap-5 border-b border-ink/15 pb-6"><div><p className="install-kicker">RBAC / ACCESS CONTROL</p><h1 className="mt-3 text-4xl font-black tracking-[-.055em] sm:text-6xl">角色与权限</h1><p className="mt-4 max-w-2xl text-sm leading-7 text-ink-muted">角色是稳定的职责边界；权限是可审计的操作能力。保存时会以事务方式替换角色授权。</p></div><ShieldCheck className="hidden size-10 text-ink-muted sm:block" /></div><div className="mt-8 grid gap-5 lg:grid-cols-[260px_1fr]"><aside className="border border-ink/15 bg-white/35 p-3"><p className="install-kicker p-3">ROLES / 角色</p>{roles.isLoading && <LoaderCircle className="m-3 size-4 animate-spin" />}{roles.data?.map((role) => <button className={`w-full border-l-2 p-3 text-left ${selectedRoleID === role.id ? "border-signal bg-ink text-white" : "border-transparent"}`} onClick={() => setDraft({ roleID: role.id, permissions: role.permissions })} key={role.id}><span className="block text-sm font-bold">{role.display_name}</span><span className="mt-1 block font-mono text-[9px] opacity-45">{role.name}</span></button>)}</aside><section className="border border-ink/15 bg-white/35 p-5 sm:p-7"><div className="flex items-center justify-between"><div><p className="text-lg font-black">{selectedRole?.display_name ?? "选择角色"}</p><p className="mt-1 font-mono text-[9px] text-ink-muted">{selectedPermissions.length} PERMISSIONS GRANTED</p></div>{selectedRole?.name === "super_admin" && <span className="install-tag">IMMUTABLE</span>}</div><div className="mt-6 grid gap-2 sm:grid-cols-2">{permissions.data?.map((permission) => { const checked = selectedPermissions.includes(permission.name); return <label className={`flex gap-3 border p-4 ${checked ? "border-ink bg-white/70" : "border-ink/10"}`} key={permission.id}><input className="sr-only" type="checkbox" checked={checked} disabled={selectedRole?.name === "super_admin"} onChange={() => setDraft({ roleID: selectedRoleID, permissions: checked ? selectedPermissions.filter((item) => item !== permission.name) : [...selectedPermissions, permission.name] })} /><span className={`mt-0.5 grid size-4 shrink-0 place-items-center border ${checked ? "border-ink bg-signal" : "border-ink/25"}`}>{checked && <Check className="size-3" />}</span><span><span className="block font-mono text-[10px] font-semibold">{permission.name}</span><span className="mt-1 block text-xs leading-5 text-ink-muted">{permission.description}</span></span></label>; })}</div>{selectedRole?.name !== "super_admin" && <button className="install-button-primary mt-6" disabled={!selectedRole || mutation.isPending} onClick={() => mutation.mutate()}>{mutation.isPending ? <LoaderCircle className="size-4 animate-spin" /> : null}保存权限</button>}</section></div></div></main>;
}
