"use client";

import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { ArrowLeft, Bot, CircleAlert, FileText, LoaderCircle, Plus, Send, Sparkles, Trash2, Upload } from "lucide-react";
import Link from "next/link";
import { useRef, useState } from "react";
import { askAI, deleteKnowledge, listConversations, listKnowledge, listMessages, uploadKnowledge } from "@/lib/ai/api";
import type { AIMessage } from "@/lib/ai/types";
import { getAPIError } from "@/lib/install/api";
import { useBilingual } from "@/lib/i18n";

export function AIWorkbench() {
  const t = useBilingual();
  const queryClient = useQueryClient(); const fileInput = useRef<HTMLInputElement>(null); const documents = useQuery({ queryKey: ["knowledge"], queryFn: listKnowledge }); const conversations = useQuery({ queryKey: ["ai-conversations"], queryFn: listConversations }); const [conversationID, setConversationID] = useState(""); const [question, setQuestion] = useState(""); const [localMessages, setLocalMessages] = useState<AIMessage[]>([]);
  const messages = useQuery({ queryKey: ["ai-messages", conversationID], queryFn: () => listMessages(conversationID), enabled: Boolean(conversationID) }); const visibleMessages = messages.data ?? localMessages;
  const upload = useMutation({ mutationFn: uploadKnowledge, onSuccess: async () => queryClient.invalidateQueries({ queryKey: ["knowledge"] }) }); const remove = useMutation({ mutationFn: deleteKnowledge, onSuccess: async () => queryClient.invalidateQueries({ queryKey: ["knowledge"] }) });
  const ask = useMutation({ mutationFn: ({ text, id }: { text: string; id?: string }) => askAI(text, id), onMutate: ({ text }) => { setLocalMessages((current) => [...current, { id: `local-${current.length}`, conversation_id: conversationID, role: "user", content: text, sources: [], tool_calls: [], input_tokens: 0, output_tokens: 0, created_at: new Date().toISOString() }]); setQuestion(""); }, onSuccess: async (answer) => { setConversationID(answer.conversation_id); setLocalMessages((current) => [...current, answer.message]); await queryClient.invalidateQueries({ queryKey: ["ai-conversations"] }); await queryClient.invalidateQueries({ queryKey: ["ai-messages", answer.conversation_id] }); } });
  const submit = () => { const text = question.trim(); if (text && !ask.isPending) ask.mutate({ text, id: conversationID || undefined }); };
  const currentError = documents.error ?? conversations.error ?? messages.error ?? upload.error ?? remove.error ?? ask.error;
  return <main className="min-h-screen bg-canvas p-5 text-ink sm:p-10"><div className="mx-auto max-w-[1550px]"><Link className="inline-flex items-center gap-2 text-xs font-bold" href="/admin"><ArrowLeft className="size-4" />{t("返回后台", "Back to admin")}</Link><header className="mt-10 border-b border-ink/15 pb-6"><p className="install-kicker">AI AGENT / TENANT KNOWLEDGE</p><h1 className="mt-3 text-4xl font-black tracking-[-.055em] sm:text-6xl">{t("企业 AI 工作台", "Enterprise AI workspace")}</h1><p className="mt-3 max-w-3xl text-sm leading-7 text-ink-muted">{t("检索当前企业知识与授权业务数据。每次工具调用、来源和 token 用量都会进入会话审计。", "Search workspace knowledge and authorized business data. Every tool call, source, and token count is retained in the conversation audit.")}</p></header>{currentError && <div className="mt-6 flex gap-2 border-l-2 border-red-800 bg-red-50 p-4 text-xs text-red-900"><CircleAlert className="size-4 shrink-0" /><span>{getAPIError(currentError)}{getAPIError(currentError).includes("provider") && t("。请配置 AI_API_KEY 后重启后端。", ". Configure AI_API_KEY and restart the backend.")}</span></div>}
    <div className="mt-7 grid min-h-[680px] gap-5 xl:grid-cols-[280px_minmax(0,1fr)_330px]"><aside className="border border-ink/15 bg-white/35 p-4"><div className="flex items-center justify-between border-b border-ink/15 pb-3"><div><p className="text-sm font-black">{t("企业知识库", "Workspace knowledge")}</p><p className="font-mono text-[9px] text-ink-muted">PGVECTOR / HNSW</p></div><button className="border border-line p-2" aria-label={t("上传知识文件", "Upload knowledge file")} onClick={() => fileInput.current?.click()}><Upload className="size-4" /></button><input className="hidden" ref={fileInput} type="file" accept=".pdf,.docx,.xlsx,.txt,.md,.csv,.json" onChange={(event) => { const file = event.target.files?.[0]; if (file) upload.mutate(file); event.target.value = ""; }} /></div>{upload.isPending && <div className="mt-4 flex items-center gap-2 text-xs"><LoaderCircle className="size-4 animate-spin" />{t("解析与向量化中", "Parsing and embedding")}</div>}<div className="mt-3 space-y-2">{documents.data?.map((document) => <div className="flex items-start gap-3 border border-ink/10 p-3" key={document.id}><FileText className="mt-0.5 size-4 shrink-0" /><div className="min-w-0 flex-1"><strong className="block truncate text-xs">{document.name}</strong><span className="font-mono text-[9px] text-ink-muted">{document.chunk_count} CHUNKS · {formatSize(document.size)}</span></div><button className="text-red-900" aria-label={t("删除文件", "Delete file")} onClick={() => remove.mutate(document.id)}><Trash2 className="size-3" /></button></div>)}</div><button className="install-button-secondary mt-5 w-full" onClick={() => fileInput.current?.click()}><Plus className="size-4" />{t("上传知识文件", "Upload knowledge file")}</button></aside>
      <section className="flex min-h-[680px] flex-col border border-ink/15 bg-white/35"><div className="flex items-center gap-3 border-b border-ink/15 p-5"><div className="grid size-10 place-items-center bg-ink text-signal"><Bot className="size-5" /></div><div><p className="font-black">NexaFlow Assistant</p><p className="font-mono text-[9px] text-ink-muted">PERMISSION-SCOPED · SOURCE-GROUNDED</p></div></div><div className="flex-1 space-y-5 overflow-y-auto p-5 sm:p-7">{visibleMessages.length === 0 && <div className="grid min-h-96 place-items-center text-center"><div><Sparkles className="mx-auto size-8 text-signal" /><p className="mt-4 text-xl font-black">{t("从企业知识开始提问", "Start with workspace knowledge")}</p><p className="mt-2 max-w-md text-xs leading-6 text-ink-muted">{t("例如：“报销政策中的住宿标准是什么？”或包含实体名称的“orders 本月金额是多少？”。", "For example: “What is the accommodation standard in the expense policy?” or “What is this month's amount for orders?”")}</p></div></div>}{visibleMessages.map((message) => <article className={`max-w-[88%] ${message.role === "user" ? "ml-auto border-r-2 border-ink bg-white p-4" : "border-l-2 border-signal bg-ink p-5 text-white"}`} key={message.id}><p className="whitespace-pre-wrap text-sm leading-7">{message.content}</p>{message.sources?.length > 0 && <div className="mt-4 border-t border-white/15 pt-3"><p className="font-mono text-[9px] text-signal">SOURCES</p>{message.sources.map((source, index) => <p className="mt-1 text-[10px] text-white/55" key={source.chunk_id}>[S{index + 1}] {source.document_name} · {(source.score * 100).toFixed(1)}%</p>)}</div>}{message.role === "assistant" && <p className="mt-3 font-mono text-[8px] opacity-35">{message.input_tokens + message.output_tokens} TOKENS · {message.tool_calls?.length ?? 0} TOOLS</p>}</article>)}</div><div className="border-t border-ink/15 p-4"><div className="flex gap-3"><textarea className="min-h-20 flex-1 resize-none border border-line bg-canvas p-3 text-sm outline-none" placeholder={t("询问企业知识或授权业务数据…", "Ask about workspace knowledge or authorized business data…")} value={question} onChange={(event) => setQuestion(event.target.value)} onKeyDown={(event) => { if (event.key === "Enter" && !event.shiftKey) { event.preventDefault(); submit(); } }} /><button className="install-button-primary self-stretch px-5" aria-label={t("发送", "Send")} disabled={!question.trim() || ask.isPending} onClick={submit}>{ask.isPending ? <LoaderCircle className="size-4 animate-spin" /> : <Send className="size-4" />}</button></div></div></section>
      <aside className="border border-ink/15 bg-ink p-5 text-white"><div className="flex items-center justify-between"><p className="text-sm font-black">{t("对话审计", "Conversation audit")}</p><button className="border border-white/20 p-2" aria-label={t("新建对话", "New conversation")} onClick={() => { setConversationID(""); setLocalMessages([]); }}><Plus className="size-3" /></button></div><p className="mt-1 font-mono text-[9px] text-white/35">USER-PRIVATE · TENANT-BOUND</p><div className="mt-5 space-y-2">{conversations.data?.map((conversation) => <button className={`w-full border-l-2 p-3 text-left ${conversationID === conversation.id ? "border-signal bg-white/10" : "border-transparent"}`} onClick={() => { setConversationID(conversation.id); setLocalMessages([]); }} key={conversation.id}><strong className="block truncate text-xs">{conversation.title}</strong><span className="font-mono text-[8px] text-white/35">{new Date(conversation.updated_at).toLocaleString()}</span></button>)}</div><div className="mt-8 border-t border-white/15 pt-5 text-[10px] leading-6 text-white/45">{t("Agent 只会调用当前用户具备权限的工具。知识向量、会话和消息均绑定当前租户；切换企业会刷新全部查询缓存。", "The agent calls only tools the current user is authorized to use. Knowledge vectors, conversations, and messages are bound to the active workspace; switching workspaces refreshes all query caches.")}</div></aside></div>
  </div></main>;
}

function formatSize(bytes: number) { return bytes < 1024 * 1024 ? `${Math.ceil(bytes / 1024)} KB` : `${(bytes / 1024 / 1024).toFixed(1)} MB`; }
